# Generated by Django 6.0.4 on 2026-06-05 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='branchmember',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.branch'),
        ),
    ]
